# web访问端口号  约定：8088
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

# 配置HikariCP数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    #    &useSSL=false&serverTimezone=UTC
    username: root
    password: admin
    hikari:
      connection-timeout: 30000 # 等待连接池分配连接的最大时长（毫秒），超时这个时长还没可用的连接则发生SQLException，默认：39秒
      minimum-idle: 5 # 最小连接数
      maximum-pool-size: 20 # 最大连接数
      auto-commit: true  # 自动提交
      idle-timeout: 600000  # 连接超时的最大时长（毫秒），超时则被释放，默认：10分钟
      pool-name: DataSourceHikariCP # 连接池名字
      max-lifetime: 1800000 # 连接的生命时长（毫秒），超时而且没被使用则被释放，默认：30分钟
      connection-test-query: select 1

# mybatis配置
mybatis:
  type-aliases-package: net.yangwenxin.pojo # 所有pojo类所在路径
  mapper-locations: classpath:mapper/*.xml  # mapper映射文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 通用Mapper配置
mapper:
  mappers: net.yangwenxin.my.mapper.MyMapper
  not-empty: false  # 在进行数据库操作的时候，判断表达式username != null，是否追加 username != ''
  identity: MYSQL
